name: PipelineWorkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
    build:
        name: Azure Pipeline
        runs-on: unbuntu-latest
        steps:
        - name: Azure Pipelines Action 
          uses: Azure/pipelines@v1
          with: 
            azure-devops-project-url: https://dev.azure.com/sharathmadasu/AgileProject
            azure-pipeline-name: 'Devops8045.gitapp'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}